name: 'GateKeeper Policies'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  GATOR_VERSION: 3.10.0
  
  
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Gather dependencies
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/bin/
        
        # install gator
        curl -L https://github.com/open-policy-agent/gatekeeper/releases/download/v${GATOR_VERSION}/gator-v${GATOR_VERSION}-linux-amd64.tar.gz -o ${GITHUB_WORKSPACE}/bin/gator.tar.gz 
        tar -xf ${GITHUB_WORKSPACE}/bin/gator.tar.gz 
        cd ${GITHUB_WORKSPACE}/bin/ && ls -R
        chmod +x ${GITHUB_WORKSPACE}/bin/gator

    - name: Update GitHub Path
      run: |
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

    - name: Test ConstraintsTemplates & Constraints
      run: |
        gator verify ./...
